
name: Continuous Integration


on:
  push:
    branches: ["main"]



jobs:

  build:
    run-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: greeting
        run: echo hello world!

      - name: done
        run: | 
          echo done!
